ARG BASE_IMAGE BASE_TAG
FROM ${BASE_IMAGE}:${BASE_TAG}
ARG KALIBR_GIT_URL="https://github.com/ethz-asl/kalibr.git"
ARG KALIBR_GIT_HASH="ee5a57d1c963249424efa64c5b6d749d2677b5e1"
ENV KALIBR_GIT_URL=${KALIBR_GIT_URL}
ENV KALIBR_GIT_HASH=${KALIBR_GIT_HASH}
ARG COMPILE_JOBS
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -qy --no-install-recommends \
    python3-dev python3-pip python3-scipy python3-matplotlib \
    ipython3 python3-wxgtk4.0 python3-tk python3-igraph \
    libpoco-dev libtbb-dev libblas-dev liblapack-dev libv4l-dev \
    && rm -rf /var/lib/apt/lists/* && \
    git config --global http.proxy ${http_proxy} && \
    git config --global https.proxy ${https_proxy} && \
    git clone ${KALIBR_GIT_URL} ${CATKIN_WORKSPACE}/src/kalibr && \
    cd ${CATKIN_WORKSPACE}/src/kalibr && \
    git checkout ${KALIBR_GIT_HASH} && \
    git config --global --unset http.proxy && \
    git config --global --unset https.proxy && \
    catkin build -w ${CATKIN_WORKSPACE} -j ${COMPILE_JOBS}
